name: gitea_ci

on:
  pull_request:
    types: closed
    branches: master
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  amd64:
    runs-on: x64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: hferreira/gitea:amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  arm64:
    runs-on: arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          push: true
          tags: hferreira/gitea:arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  manifest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker manifest create hferreira/gitea:latest \
            --amend hferreira/gitea:arm64 \
            --amend hferreira/gitea:amd64 && \
          docker manifest push hferreira/gitea:latest
